image: acr.run/concretecloud/chirp/sphinx

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - export LC_ALL=C.UTF-8

stages:
  - docs

make-docs:
  only:
    - master
  stage: docs
  script:
    - apt-get update
    - apt-get -y install libuv1-dev libssl-dev python3-dev python3-pip python3 python3-sphinx python3-sphinx-rtd-theme graphviz build-essential
    - pip3 install cffi
    - python3 libchirp_cffi.py
    - cd doc
    - make html
  artifacts:
    paths:
      - doc/_build/html/*
